// config for classic-starter.c — the original startup default, preserved for posterity.
// slot 0 = the little explorer (player), slot 1 = the metal floor tile.
// The original default shipped blank and asked you to draw these yourself; we bake
// in simple versions so the thumbnail looks like the demo was meant to look.

module.exports = {
  sprites: {
    // slot 0 — explorer: white helmet, blue visor, blue suit, grey boots
    0: `
................
.....WWWWWW.....
....WWWWWWWW....
....WbbbbbbW....
....WbbbbbbW....
....WWWWWWWW....
.....WWWWWW.....
....bBBBBBBb....
...bBBBBBBBBb...
...bBBBBBBBBb...
...bBBBBBBBBb...
....BB....BB....
....BB....BB....
....SS....SS....
................
................
`,
    // slot 1 — metal floor panel: light-grey frame, riveted slate squares
    1: `
LLLLLLLLLLLLLLLL
LWWWWWWWWWWWWWWL
LWLLLLLLLLLLLLWL
LWLSSLLSSLLSSLWL
LWLSSLLSSLLSSLWL
LWLLLLLLLLLLLLWL
LWLLLLLLLLLLLLWL
LWLSSLLSSLLSSLWL
LWLSSLLSSLLSSLWL
LWLLLLLLLLLLLLWL
LWLLLLLLLLLLLLWL
LWLSSLLSSLLSSLWL
LWLSSLLSSLLSSLWL
LWLLLLLLLLLLLLWL
LWWWWWWWWWWWWWWL
LLLLLLLLLLLLLLLL
`,
  },
}
