// excitebike.cart.js — two sprites for excitebike.c
// slot 1 = bike + rider (level, facing right). The rider's shirt is drawn in
//          RED (index 8) — the "magic color" pal()-swapped per CPU rider.
// slot 2 = crash / wipeout (rider thrown, bike on its side)
//
// chars (DEFAULT_CHAR_MAP): 7=white  c=blue(visor)  R=red(shirt, recolored)
//   1=dark blue(pants)  L=light grey(frame)  S=dark grey(wheels)  p=peach(hand)  .=transparent

module.exports = {
  sprites: {

    // slot 1 — bike + rider, level, facing right
    1: `
................
................
........77......
.......7cc7.....
.......7777.....
......RRRR......
.....RRRRRp.....
.....RRRR.p.....
....1RRR1.......
...11...1.......
..LLLLLLLLLLL...
..L..LL...L.L...
.SSS.....SSS....
SS5SS...SS5SS...
.SSS.....SSS....
..S.......S.....
`,

    // slot 2 — wipeout (rider tumbling, bike on its side)
    2: `
................
................
.......77.......
......7cc7......
....RRRRR.......
...RRRRRRR......
...1RR.RR1......
..11....11......
................
...........LLL..
.SSS......L...L.
SS5SS.....L.SSS.
.SSS.......SS5SS
..S........SSS..
............S...
................
`,

  },
}
