// Sprites for outrun.c — billboard cars (with little passengers) + roadside props.
//
// Slot layout (8-col sheet):
//   1 player car (rear view, fixed red)
//   2 traffic car (rear view) — body painted in MAGIC index 28, recoloured per car
//   3 palm    4 cactus    5 pine    6 city tower    7 rock
//
// Magic colour: the traffic body is index 28 ('m'); the cart calls pal(28, col)
// before drawing each car so one sprite yields a whole rainbow of traffic.
// Two passenger heads (peach 'p' + brown hair 'N') show through the rear window.
// Outlines use index 16 ('x') — reads near-black but is never the transparent 0.

module.exports = {
  charMap: { 'm': 28, 'x': 16 },

  sprites: {
    // ---- player car (red, rear view) ----
    1: `
................
......xxxxxx....
....xRRRRRRRRx..
...xRRRRRRRRRRx.
...xRBBBBBBBBRx.
...xRBNBBBBNBRx.
...xRBpBBBBpBRx.
...xRRRRRRRRRRx.
..xRRRRRRRRRRRRx
..xRRRRRRRRRRRRx
..xYRRRRRRRRRRYx
..xRRRRRRRRRRRRx
..xxSSxxxxxxSSxx
..xSSSxxxxxxSSSx
....xx......xx..
................
`,
    // ---- traffic car (magic body 'm') ----
    2: `
................
......xxxxxx....
....xmmmmmmmmx..
...xmmmmmmmmmmx.
...xmBBBBBBBBmx.
...xmBNBBBBNBmx.
...xmBpBBBBpBmx.
...xmmmmmmmmmmx.
..xmmmmmmmmmmmmx
..xmmmmmmmmmmmmx
..xYmmmmmmmmmmYx
..xmmmmmmmmmmmmx
..xxxxxxxxxxxxxx
..xxxxxxxxxxxxxx
....xx......xx..
................
`,
    // ---- palm tree ----
    3: `
.......gg.......
....gg.gg.gg....
..ggggggggggg...
.gggggNNNgggggg.
...ggNNNNNgg....
.....NNNNN......
......NNN.......
......NNN.......
......NNN.......
......NNN.......
......NNN.......
......NNN.......
.....NNNNN......
....gNNNNNg.....
...gggGGGggg....
................
`,
    // ---- cactus ----
    4: `
......gg........
......gg........
..gg..gg........
..gg..gg...gg...
..gg..gg...gg...
..gggggg...gg...
......gg.gggg...
......gggg......
......gg........
......gg........
......gg........
......gg........
.....Gggg.......
....NNNNNN......
....NNNNNN......
................
`,
    // ---- pine ----
    5: `
.......G........
......GGG.......
......ggg.......
.....GGGGG......
.....ggggg......
....GGGGGGG.....
....ggggggg.....
...GGGGGGGGG....
...ggggggggg...
..GGGGGGGGGGG...
..ggggggggggg...
.....NNNN.......
.....NNNN.......
.....NNNN.......
....xNNNNx......
................
`,
    // ---- city tower ----
    6: `
.xSSSSSSSSSSx...
.xScScScScSx....
.xSSSSSSSSSSx...
.xScScScScSx....
.xSSSSSSSSSSx...
.xScScScScSx....
.xSSSSSSSSSSx...
.xScScScScSx....
.xSSSSSSSSSSx...
.xScScScScSx....
.xSSSSSSSSSSx...
.xScScScScSx....
.xSSSSSSSSSSx...
.xSSSSSSSSSSx...
.xxxxxxxxxxxx...
................
`,
    // ---- rock ----
    7: `
................
................
................
.....xxxx.......
....xSSSSx......
...xSSSSSSx.....
...xSLLSSSx.....
..xSSSSSSSSx....
..xSSSSSSSSx....
..xSSSSSSSSx....
..xSSSSSSSSx....
...xxxxxxxx.....
................
................
................
................
`,
  },
}
