// platform.cart.js — sprites + map for platform.c
// Tile 1=brick, 2=grass-top, 3=coin, 4=player fr1, 5=player fr2, 6=enemy fr1, 7=enemy fr2

module.exports = {
  sprites: {

    // slot 1 — solid brick tile
    1: `
SSSSSSSSSSSSSSSS
SNNNNNNNSNNNNNNS
SNNNNNNNSNNNNNNS
SNNNNNNNSNNNNNNS
SNNNNNNNSNNNNNNS
SNNNNNNNSNNNNNNS
SNNNNNNNSNNNNNNS
SSSSSSSSSSSSSSSS
SNNNNNNNNNNNNNNS
SNNNNNNNNNNNNNNS
SNNNNNNNNNNNNNNS
SNNNNNNNNNNNNNNS
SNNNNNNNNNNNNNNS
SNNNNNNNNNNNNNNS
SNNNNNNNNNNNNNNS
SSSSSSSSSSSSSSSS
`,

    // slot 2 — grass-top tile (solid, green on top / brown dirt below)
    2: `
GGGgGGGGgGGGgGGG
gggggggggggggggg
GgGgGgGgGgGgGgGg
GgGgGgGgGgGgGgGg
NNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNN
`,

    // slot 3 — coin (yellow with white shine)
    3: `
................
................
......YYYY......
.....YYYYYY.....
....YYWWYYYY....
....YYWWYYYY....
....YYYYYYYY....
....YYYYYYYY....
....YYYYYYYY....
....YYYYYYYY....
.....YYYYYY.....
......YYYY......
................
................
................
................
`,

    // slot 4 — player walk frame 1 (red cap, blue overalls)
    4: `
.....RRRRR......
....RRRRRRR.....
...RRWWWWWRR....
...RWWWWWWWR....
...RWNWWNWNR....
....WWWWWWW.....
....bbbbbbb.....
...bbbbbbbbb....
...bbbbbbbbb....
....bbbbbbb.....
.....BB.BB......
....BBB.BBB.....
....NNN.NNN.....
....N.....N.....
................
................
`,

    // slot 5 — player walk frame 2 (legs spread)
    5: `
.....RRRRR......
....RRRRRRR.....
...RRWWWWWRR....
...RWWWWWWWR....
...RWNWWNWNR....
....WWWWWWW.....
....bbbbbbb.....
...bbbbbbbbb....
...bbbbbbbbb....
....bbbbbbb.....
....BB...BB.....
...BBB...BBB....
...NNN...NNN....
...N.....N......
................
................
`,

    // slot 6 — enemy frame 1 (red round critter with eyes)
    6: `
................
....RRRRRRRR....
...RRRRRRRRRR...
..RRRRRRRRRRRR..
..RRWWRRRWWRRRR.
..RRKRRRRKRRRRR.
..RRRRRRRRRRRR..
..RRRRRRRRRRR...
...RRRRRRRRRRR..
....RRRRRRRR....
....RR....RR....
....NN....NN....
....NNNNNNNN....
................
................
................
`,

    // slot 7 — enemy frame 2 (legs swapped)
    7: `
................
....RRRRRRRR....
...RRRRRRRRRR...
..RRRRRRRRRRRR..
..RRWWRRRWWRRRR.
..RRKRRRRKRRRRR.
..RRRRRRRRRRRR..
...RRRRRRRRRRR..
..RRRRRRRRRRRR..
....RRRRRRRR....
...RR......RR...
...NN......NN...
...NNNNNNNNNN...
................
................
................
`,

  },

  map: {
    // '#'=brick(1)  'G'=grass(2)  'C'=coin(3)  ' '=empty
    // 80 columns wide, 19 rows tall
    tiles: { '#': 1, 'G': 2, 'C': 3 },
    layout: [
      '                                                                                ',
      '                                                                                ',
      '           C       C                   C       C              C                ',
      '          GGGGG   GGGGG               GGGGG   GGGGG         GGGGG              ',
      '                                                                                ',
      '    C  C             C   C                    C   C                C  C        ',
      '   GGGGG           GGGGG GGGGG              GGGGG GGGGG          GGGGG         ',
      '                                                                                ',
      '        C   C   C                  C   C   C                  C   C   C        ',
      '       GGGGG GGGGG              GGGGG GGGGG               GGGGG GGGGG          ',
      '                                                                                ',
      '  C                C   C                    C   C                           C  ',
      ' GGGGG            GGGGG GGGGG             GGGGG GGGGG                    GGGGG ',
      '                                                                                ',
      '      GGG     GGG     GGG     GGG     GGG     GGG     GGG     GGG             ',
      '                                                                                ',
      'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
      '################################################################################',
      '################################################################################',
    ],
  },
}
