#!/usr/bin/env node
// filter-spec.js — measure a per-voice FILTER's actual frequency response: slope, resonance
// peak, and passband-bass drain. wav-analyze measures levels, tune-check measures pitch —
// this measures the CIRCUIT. Born from the rebirth-classic 303-fidelity spike
// (docs/design/rebirth-classic.md §3): "is our filter right?" should be a number, not vibes.
//
//   node tools/filter-spec.js                     report on low + ladder + steiner (DEFAULT)
//   node tools/filter-spec.js --modes low,ladder  subset (low|ladder|steiner)
//   node tools/filter-spec.js --json              machine-readable
//   node tools/filter-spec.js --keep              keep the WAV/trace/cart (build/.filterspec/)
//
// How: generates a throwaway probe cart (tune-check RECIPE pattern) that holds a SAW at A1
// (55 Hz — a dense harmonic comb) through one filter config per 1s segment: first FILTER_OFF
// (the reference comb), then per mode a cutoff ladder at res 0 (slope) and a resonance sweep
// at fixed cutoff (peak + bass drain). Renders deterministically via play.js --wav, locates
// each segment from the trace, measures every harmonic with Goertzel, and reports the
// RESPONSE (filtered minus reference, in dB) per harmonic:
//
//   slope    dB/oct fitted on harmonics between 2×fc and 4×fc (res 0). A 2-pole SVF should
//            read ≈ −12, a 4-pole ladder ≈ −24 (single-rate warping bends the far tail).
//   peak     max response near fc as res climbs — how the resonance actually rings.
//   fund     response AT the fundamental (55 Hz, deep in the passband) as res climbs —
//            the ladder's signature "loses bass as resonance rises" is this number going
//            negative; a compensated/SVF filter stays ≈ 0.
//
// CAVEAT: STEINER has tanh nonlinearities in the loop, so its "response" is amplitude-
// dependent — what's reported is its behavior at this probe's level (vol 7), which is the
// honest, cart-realistic question anyway. Same story if a drive stage is ever measured.
//
// The numbers are deterministic (same engine + same probe = identical bytes), so a saved
// report diffs cleanly across engine changes — cite it as acceptance evidence when touching
// sound.h filter code (checks-and-oracles: render/audio row).

const fs = require('fs')
const path = require('path')
const { spawnSync } = require('child_process')

const ROOT = path.resolve(__dirname, '..')

// ── probe schedule ──────────────────────────────────────────────────────────
const MODES = { low: 1, ladder: 5, steiner: 6, diode: 10 }   // FILTER_* in studio.h
const MODE_LABEL = { low: 'FILTER_LOW (Chamberlin SVF, 2-pole)', ladder: 'FILTER_LADDER (ZDF transistor ladder, 4-pole)', steiner: 'FILTER_STEINER (2-pole, tanh feedback)', diode: 'FILTER_DIODE (ZDF diode ladder, stage-3 tap, tanh loop)' }
const F0_MIDI = 33, F0_HZ = 55                               // A1 — harmonic comb every 55 Hz
const SLOPE_CUTS = [400, 800, 1600]                          // res 0: knee + slope per cutoff
const RES_SWEEP = [0, 4, 8, 10, 12, 15]                      // fixed fc: ring + bass drain
const RES_FC = 600
const NF = 60, GAP = 12, PER = NF + GAP                      // frames: 1s tone, 0.2s silence
const MEASURE_A = 0.35, MEASURE_B = 0.85                     // measure the steady sustain

function buildSchedule(modeNames) {
  const segs = [{ mode: 0, cut: 8000, res: 0, label: 'REF (FILTER_OFF)', kind: 'ref' }]
  for (const m of modeNames) {
    for (const c of SLOPE_CUTS) segs.push({ mode: MODES[m], cut: c, res: 0, label: `${m} fc=${c} res=0`, kind: 'slope', m, c })
    for (const r of RES_SWEEP) segs.push({ mode: MODES[m], cut: RES_FC, res: r, label: `${m} fc=${RES_FC} res=${r}`, kind: 'res', m, r })
  }
  return segs
}

// ── probe cart (generated, tune-check RECIPE pattern) ───────────────────────
function renderProbe(segs, keep) {
  const dir = path.join(ROOT, 'build', '.filterspec')
  fs.mkdirSync(dir, { recursive: true })
  const wav = path.join(dir, 'probe.wav'), trace = path.join(dir, 'probe.trace.jsonl')
  const cartName = '_filterspecgen'
  const cartPath = path.join(ROOT, 'tools', 'carts', `${cartName}.c`)
  const src = `#include "studio.h"
#include <stdio.h>
// GENERATED by tools/filter-spec.js — safe to delete.
#define NF ${NF}
#define PER ${PER}
static const int MODE[] = { ${segs.map(s => s.mode).join(', ')} };
static const int CUT[]  = { ${segs.map(s => s.cut).join(', ')} };
static const int RES[]  = { ${segs.map(s => s.res).join(', ')} };
#define NS ((int)(sizeof(MODE)/sizeof(MODE[0])))
static int fnum = -1, held = -1;
void init(void) { instrument(5, INSTR_SAW, 4, 30, 7, 30); }
void update(void) {
  fnum++;
  int idx = fnum / PER, local = fnum % PER;
  if (idx < NS) {
    if (local == 0) {
      instrument_filter(5, MODE[idx], CUT[idx], RES[idx]);
      held = note_on(${F0_MIDI}, 5, 7);
    } else if (local == NF - 1 && held >= 0) { note_off(held); held = -1; }
  }
#ifdef DE_TRACE
  watch("seg", "%d", idx < NS ? idx : -1);
#endif
}
void draw(void) { cls(0); }
`
  fs.writeFileSync(cartPath, src)
  try {
    const frames = segs.length * PER + 30
    const r = spawnSync('node',
      [path.join('tools', 'play.js'), cartName, 'run', '--headless',
       '--frames', String(frames), '--trace', trace, '--wav', wav],
      { cwd: ROOT, encoding: 'utf8' })
    if (r.status !== 0) {
      process.stderr.write((r.stdout || '') + (r.stderr || ''))
      throw new Error(`render failed (play.js ${cartName})`)
    }
  } finally { if (!keep) fs.rmSync(cartPath, { force: true }) }
  return { wav, trace, dir }
}

// ── WAV + trace readers (tune-check house pattern) ──────────────────────────
function readWavMono(file) {
  const b = fs.readFileSync(file)
  if (b.toString('ascii', 0, 4) !== 'RIFF' || b.toString('ascii', 8, 12) !== 'WAVE')
    throw new Error(`${file}: not a WAV`)
  let off = 12, fmt = null, data = null
  while (off + 8 <= b.length) {
    const id = b.toString('ascii', off, off + 4)
    const len = b.readUInt32LE(off + 4)
    if (id === 'fmt ') fmt = { ch: b.readUInt16LE(off + 10), sr: b.readUInt32LE(off + 12), bits: b.readUInt16LE(off + 22) }
    if (id === 'data') data = { off: off + 8, len }
    off += 8 + len + (len & 1)
  }
  if (!fmt || !data || fmt.bits !== 16) throw new Error(`${file}: expected 16-bit PCM WAV`)
  const ch = fmt.ch, n = Math.floor(data.len / 2 / ch)
  const s = new Float64Array(n)
  for (let i = 0; i < n; i++)
    s[i] = ch === 1 ? b.readInt16LE(data.off + i * 2) / 32768
                    : (b.readInt16LE(data.off + i * 2 * ch) + b.readInt16LE(data.off + i * 2 * ch + 2)) / 65536
  return { sr: fmt.sr, s }
}

function segFrames(trace, nSegs) {
  // first + last frame per segment index, from the watch("seg") stream
  const first = new Array(nSegs).fill(-1), last = new Array(nSegs).fill(-1)
  let lastFrame = 0
  for (const line of fs.readFileSync(trace, 'utf8').split('\n')) {
    if (!line.trim()) continue
    let j; try { j = JSON.parse(line) } catch { continue }
    lastFrame = j.f
    const seg = j.w && Number(j.w.seg)
    if (seg >= 0 && seg < nSegs) { if (first[seg] < 0) first[seg] = j.f; last[seg] = j.f }
  }
  return { first, last, lastFrame }
}

// ── measurement ─────────────────────────────────────────────────────────────
function goertzel(s, a, b, sr, f) {
  // Hann-windowed Goertzel magnitude at f over samples [a, b)
  const n = b - a
  const w = 2 * Math.PI * f / sr, cw = 2 * Math.cos(w)
  let s0 = 0, s1 = 0, s2 = 0
  for (let i = 0; i < n; i++) {
    const hann = 0.5 - 0.5 * Math.cos(2 * Math.PI * i / (n - 1))
    s0 = s[a + i] * hann + cw * s1 - s2
    s2 = s1; s1 = s0
  }
  const re = s1 - s2 * Math.cos(w), im = s2 * Math.sin(w)
  return Math.sqrt(re * re + im * im) / (n / 4)   // Hann coherent-gain normalize
}

function harmonicLevels(s, sr, a, b, maxHz) {
  const H = Math.floor(Math.min(maxHz, sr * 0.45) / F0_HZ)
  const lv = new Float64Array(H + 1)
  for (let h = 1; h <= H; h++) lv[h] = goertzel(s, a, b, sr, h * F0_HZ)
  return lv
}

const db = (x) => 20 * Math.log10(Math.max(x, 1e-12))

function fitSlope(resp, fc) {
  // dB/oct on harmonics with h·55 in [2fc, 4fc] — past the knee, before the noise floor
  const pts = []
  for (let h = 1; h < resp.length; h++) {
    const f = h * F0_HZ
    if (f >= 2 * fc && f <= 4 * fc && isFinite(resp[h])) pts.push([Math.log2(f), resp[h]])
  }
  if (pts.length < 3) return NaN
  const n = pts.length
  const sx = pts.reduce((t, p) => t + p[0], 0), sy = pts.reduce((t, p) => t + p[1], 0)
  const sxx = pts.reduce((t, p) => t + p[0] * p[0], 0), sxy = pts.reduce((t, p) => t + p[0] * p[1], 0)
  return (n * sxy - sx * sy) / (n * sxx - sx * sx)
}

function peakNear(resp, fc) {
  let best = -Infinity
  for (let h = 1; h < resp.length; h++) {
    const f = h * F0_HZ
    if (f >= 0.5 * fc && f <= 1.6 * fc) best = Math.max(best, resp[h])
  }
  return best
}

// ── main ────────────────────────────────────────────────────────────────────
function main() {
  const argv = process.argv.slice(2)
  const has = (f) => argv.includes(f)
  const val = (f, d) => { const i = argv.indexOf(f); return i >= 0 ? argv[i + 1] : d }
  const modeNames = val('--modes', 'low,ladder,steiner,diode').split(',').map(s => s.trim()).filter(Boolean)
  for (const m of modeNames) if (!(m in MODES)) { console.error(`unknown mode "${m}" — one of: ${Object.keys(MODES).join(', ')}`); process.exit(2) }

  const segs = buildSchedule(modeNames)
  const { wav, trace, dir } = renderProbe(segs, has('--keep'))
  const { sr, s } = readWavMono(wav)
  const { first, last, lastFrame } = segFrames(trace, segs.length)
  const spf = s.length / (lastFrame + 1)

  // per-segment harmonic levels over the steady window
  const levels = segs.map((seg, i) => {
    if (first[i] < 0) return null
    const a = Math.round((first[i] + NF * MEASURE_A) * spf)
    const b = Math.round((first[i] + NF * MEASURE_B) * spf)
    return harmonicLevels(s, sr, a, Math.min(b, s.length), 7000)
  })
  const ref = levels[0]
  if (!ref) throw new Error('reference segment missing from trace')
  const resp = levels.map(lv => lv && Array.from(lv, (x, h) => h === 0 ? NaN : db(x) - db(ref[h])))

  // assemble per-mode results
  const out = { f0_hz: F0_HZ, res_fc: RES_FC, modes: {} }
  segs.forEach((seg, i) => {
    if (seg.kind === 'ref' || !resp[i]) return
    const m = (out.modes[seg.m] ||= { slope: {}, res: {} })
    if (seg.kind === 'slope') m.slope[seg.c] = { dbPerOct: fitSlope(resp[i], seg.c), peak: peakNear(resp[i], seg.c) }
    else m.res[seg.r] = { peak: peakNear(resp[i], RES_FC), fund: resp[i][1] }
  })

  if (has('--json')) { console.log(JSON.stringify(out, null, 2)); return }

  console.log(`filter-spec — saw @ A1 (${F0_HZ} Hz), response vs FILTER_OFF, dB  (render: ${path.relative(ROOT, wav)}${has('--keep') ? ' kept' : ''})`)
  for (const m of modeNames) {
    const r = out.modes[m]; if (!r) continue
    console.log(`\n${MODE_LABEL[m]}`)
    const slopes = SLOPE_CUTS.map(c => `fc=${c}: ${r.slope[c].dbPerOct.toFixed(1)}`).join('   ')
    console.log(`  slope (res 0, fit 2–4×fc)   ${slopes}   dB/oct`)
    const peaks = RES_SWEEP.map(x => `${x}:${r.res[x].peak >= 0 ? '+' : ''}${r.res[x].peak.toFixed(1)}`).join('  ')
    console.log(`  res peak @fc=${RES_FC} (res→dB)  ${peaks}`)
    const funds = RES_SWEEP.map(x => `${x}:${r.res[x].fund >= 0 ? '+' : ''}${r.res[x].fund.toFixed(1)}`).join('  ')
    console.log(`  fundamental 55 Hz (res→dB)  ${funds}   ← bass drain if this falls`)
  }
  console.log('\n(303 target: ~18 dB/oct, strong ringing peak, audible bass drain as res climbs — audio-notes §17 / rebirth-classic §3)')
}

main()
